version: "3.7"

services:
    app:
        image: exercise:latest
        ports:
            - 4000:4000
        environment:
            PGUSER: postgres
            PGHOST: bd_postgres
            PGPASSWORD: postgres
            PGPORT: 5432
            PGDATABASE: devops

    bd_postgres:
        image: app.bd:latest
        ports:
          - 5000:5432
        environment:
            POSTGRES_PASSWORD: postgres