version: "3.7"

services:
    app:
        image: exercise:latest
        ports:
            - 4000:4000
        volumes:
            - ./app/server.js:/app/server.js
        environment:
            PGUSER: postgres
            PGHOST: bd_postgres
            PGPASSWORD: postgres
            PGPORT: 5432
            PGDATABASE: devops

    bd_postgres:
        image: postgres:13.8
        expose:
          - 5432
        ports:
          - 3000:5432
        volumes:
            - ./app/config/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            POSTGRES_PASSWORD: postgres