version: "3.8"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  app:
      image: exercise:latest
      environment:
          - VIRTUAL_HOST=localhost:80
          - PGUSER=postgres
          - PGHOST=bd_postgres
          - PGPASSWORD=postgres
          - PGPORT=5432
          - PGDATABASE=devops

  bd_postgres:
      image: app.bd:latest
      ports:
        - 5000:5432
      environment:
          POSTGRES_PASSWORD: postgres