version: "3.7"

services:
    postgres:
        image: postgres:13.8
        expose:
          - 5432
        ports:
          - 3000:5432
        volumes:
            - ./app/config/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            POSTGRES_PASSWORD: postgres