version: '3.9'

services:
  bd_postgres:
      image: "${IMAGE_BD}"
      environment:
        POSTGRES_PASSWORD: postgres

  api:
    image: "${IMAGE_APP}"
    depends_on:
      - bd_postgres
    environment:
      - PGUSER=postgres
      - PGHOST=bd_postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
      - PGDATABASE=devops

  nginx:
    image: "${IMAGE_PROXY}"
    depends_on:
      - api
    ports:
      - 9090:4000

