version: '3.9'

services:
  bd_postgres:
      image: app.bd:latest
      environment:
        POSTGRES_PASSWORD: postgres

  api:
    image: exercise:latest
    depends_on:
      - bd_postgres
    environment:
      - PGUSER=postgres
      - PGHOST=bd_postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
      - PGDATABASE=devops

  nginx:
    image: proxy:latest
    depends_on:
      - api
    ports:
      - 9090:4000

