version: '3.9'

services:
  bd_postgres:
      image: "${IMAGE_BD}"
      environment:
        POSTGRES_PASSWORD: postgres

# Las credenciales aun quedaron pendientes de configurarse,
# se haria uso de la secret manager para generar y obtener a traves de la cli de aws la clave,
# se puede ver el avance en el archivo /makefiles/secret.mk

  api:
    image: "${IMAGE_APP}"
    depends_on:
      - bd_postgres
    environment:
      - PGUSER=postgres
      - PGHOST=bd_postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
      - PGDATABASE=devops

  nginx:
    image: "${IMAGE_PROXY}"
    depends_on:
      - api
    ports:
      - 9090:4000

